### ISSUE TITLE
Grab pyjnius.jar from a Maven repository

### ISSUE THREAD

**Issue by ctrueden** [scijava/scyjava#11]
Right now, if `${sys.prefix}/share/pyjnius/pyjnius.jar` exists, it is added to the local classpath when spinning up Java. (See 8b2db29d85d393c5d483a000ea896245f6d5d01f.) However, we can do better: we can add pyjnius to the jgo endpoint as a remote Maven artifact, and then it never needs to be available locally. And then if necessary, set `PYJNIUS_JAR` to match where it gets cached locally. This would make life a bit simpler for non-conda pip users.

**Comment by ctrueden** [comment]
@hanslovsky Aah, we were so busy, I forgot to follow up with you on this. Maybe we have time to figure it out remotely over the next month or so...

**Comment by hanslovsky** [comment]
AFAIK pyjnius.jar is very stable, so we might be able to just upload it (on scijava public), so we can just treat it like any other jar. Do we need `groupId` and `version` tags in order to upload to scijava public? Maybe we could just build it once with every release and upload to scijava public with that version and `kivy` or similar `groupId` (of course we would need to ask for permission first).

> And then if necessary, set `PYJNIUS_JAR` to match where it gets cached locally.

`PYJNIUS_JAR` should be completely obsolete if we can fetch through jgo like all other jars.

**Comment by ctrueden** [comment]
Will be moot with the switch to JPype.
