### ISSUE TITLE
 convert <java array 'int[]'> to python object

### ISSUE THREAD

**Issue by rmd13** [scijava/scyjava#28]
Hi,
I get a java int[] from java API, and want to get  as python variable.
However, to_python only support int, not int[].
I can convert each number one-after-one, but is there an easier way to convert the whole?
Thanks.

**Comment by imagejan** [comment]
scyjava uses jpype, so maybe this helps:

https://jpype.readthedocs.io/en/latest/quickguide.html#primitives

**Comment by Thrameos** [comment]
Can I ask why not apply the ``list`` type conversion?

```
ja = jpype.JInt[5]
ja[0]=1
ja[1]=2
ja[2]=3
ja[3]=4
ja[4]=5
print(type(ja)) # => <java class 'int[]'>
pa = list(ja)
print(pa) # => [1,2,3,4,5]
print(type(pa)) # => <class 'list'>
```

**Comment by rmd13** [comment]
> scyjava uses jpype, so maybe this helps:
> 
> https://jpype.readthedocs.io/en/latest/quickguide.html#primitives

Hi, thanks.
The problem is that the variable is not constructed in python using JInt, but returned from java method inside jar packages.

**Comment by imagejan** [comment]
@rmd13 can you just write `list(your_java_int_array)` without using `to_python` or anything?

**Comment by Thrameos** [comment]
@rmd13 For reference the reason that JPype returns a ``JInt[]`` rather than a Python type is that conversion costs a lot time so it is our policy to always require explicit casting.   After all if someone want to get one element out of a 10MByte array with ``obj.callMethod()[5]`` the we would have converted 10 MBytes of integers into list elements just to chuck them all.  

JPype provides conversions through duck typing.   That is by pretending to be a Python type (like list or dict) at the interface level, you can simply call the standard conversion routine in Python such as ``str``, ``list``, or ``dict``.   That make it clear the copy is being taken.   JPype conversions will be "shallow" as opposed to ``to_python`` in which it is attempting a "deep" conversion of all elements in tree of objects.  "deep" conversion is more problematic as you have to have every conversion defined.   Should a ``JInt[]`` got to a ``tuple`` or a ``list`` or left alone?  Does ``Instant`` go to ``str`` or ``datetime.datetime`` or get left as Java object?  As these are arbitrary decision JPype makes no attempt to provide them.  Any decision may be right in one situation and wrong in another.   

Not that this is addressing your issue, but hopefully gives you some background on why things work the way they do.  

@imagejan I am guessing in this case the ``JInt[]`` may be embedded in a structure which to_python was called on.   As per the usual problems with deep copies this item was not converted as there was no definition of ``JInt[]=>list()``.  I suppose you could give a map argument to the ``to_python`` method so that the user could impose a specific conversion with ``to_python(obj, {JInt[]:list, JChar[]:str})`` where a dict gives a list of type to converter pairs.   But I rejected that concept from JPype for the reasons that I have stated with deep copy.

**Comment by rmd13** [comment]
the list() method works well as you suggested. 
Many thanks yo to you all.
