### ISSUE TITLE
Exclude Jpype 1.5.1

### ISSUE THREAD

**Issue by hinerm** [scijava/scyjava#70]
See https://github.com/imagej/napari-imagej/issues/316 and https://github.com/jpype-project/jpype/issues/1242

**Comment by ctrueden** [comment]
The root cause will need to be fixed upstream in jpype. Doing `jpype != 1.5.1` or whatever won't be a good solution if jpype 1.5.2 is released and still has the problem. Based on the discussion in jpype-project/jpype#1242, I do not think anybody has hit upon the actual root cause yet; I doubt it's incomplete JDKs, and someone already chimed in saying the `PATH` != `JAVA_HOME` theory is incorrect, too. If someone impacted by the problem is able to debug into the jpype code to see what goes wrong, that would be better.

**Comment by ctrueden** [comment]
In the meantime: I suggest we do `jpype <= 1.5.0` instead, just to be safe.

**Comment by elevans** [comment]
Agreed.

**Comment by elevans** [comment]
Done a607b5c93d03af695916e25527e67ea9fbbced7a.

**Comment by imagejan** [comment]
Jpype 1.5.2 was release recently: https://github.com/jpype-project/jpype/releases/tag/v1.5.2

Maybe it's enough to limit to `!=1.5.1` now?
